version : "3.9"
services :
    web-server:
        networks: 
            - lamp-net 
        ports: 
            - 80:80
        container_name: php-apache
        build: ./php-apache
        environment: 
            DB_USER: ${MYSQL_USER}
            DB_PASS: ${MYSQL_PASSWORD}
            DB_NAME: ${MYSQL_DATABASE}

    
    mysql-server:
        networks:
            - lamp-net
        ports: 
            - 3306:3306
        container_name: mysql-server
        image: "mysql:8.4"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
    lamp-net: {}